# Generated by Django 4.1.5 on 2024-06-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_id',
        ),
    ]
