# Generated by Django 4.2.6 on 2024-06-12 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notification', '0002_alter_media_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='uploaded_by',
            new_name='created_by',
        ),
        migrations.CreateModel(
            name='TrashMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(blank=True, choices=[('archive', 'Image'), ('upload', 'Video')], max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media_files/')),
                ('student', models.BooleanField(default=False)),
                ('teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('trashed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notification.department')),
            ],
        ),
    ]
