# Generated by Django 4.2.6 on 2024-06-12 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notification', '0003_rename_uploaded_at_media_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashmedia',
            name='trashed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trashed_trashmedia_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trashmedia',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trashmedia_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
