# Generated by Django 4.2.6 on 2024-06-22 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notification', '0004_trashmedia_trashed_by_alter_trashmedia_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Notification.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trashmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('archive', 'Archive'), ('upload', 'Uploads')], max_length=20, null=True),
        ),
    ]
