# Generated by Django 4.2.6 on 2024-02-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0004_student_department_student_user_teacher_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='admn_no',
        ),
    ]
