# Generated by Django 4.1.5 on 2024-02-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Notification", "0005_rename_student_id_student_admn_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="department",
            new_name="dept_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="department",
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pgm_name", models.CharField(max_length=50)),
                ("grad_level", models.CharField(max_length=10)),
                (
                    "dept_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Notification.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="pgm_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Notification.programme",
            ),
        ),
    ]
