# Generated by Django 4.2.6 on 2024-06-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0006_remove_student_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_category',
            field=models.CharField(choices=[('examination', 'Examination'), ('department', 'Department'), ('notice', 'Notics'), ('order', 'Order')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('archive', 'Archive'), ('upload', 'Upload')], max_length=20, null=True),
        ),
    ]
