# Generated by Django 4.1.5 on 2024-02-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notification", "0006_rename_department_teacher_dept_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="pgm_id",
            new_name="pgm",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="dept_id",
            new_name="dept",
        ),
    ]
