# Generated by Django 4.2.6 on 2024-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0007_media_media_category_alter_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashmedia',
            name='media_category',
            field=models.CharField(choices=[('examination', 'Examination'), ('department', 'Department'), ('notice', 'Notics'), ('order', 'Order')], max_length=50, null=True),
        ),
    ]
