# Generated by Django 4.1.5 on 2024-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notification", "0008_alter_student_admn_no_alter_teacher_hod_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="admission_no",
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "male"), ("Female", "female"), ("Other", "other")],
                default="Male",
                max_length=10,
            ),
        ),
    ]
