# Generated by Django 4.2.6 on 2024-06-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0009_alter_media_created_at_alter_trashmedia_trashed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notification.department'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_category',
            field=models.CharField(blank=True, choices=[('examination', 'Examination'), ('department', 'Department'), ('notice', 'Notice'), ('order', 'Order')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trashmedia',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notification.department'),
        ),
        migrations.AlterField(
            model_name='trashmedia',
            name='media_category',
            field=models.CharField(blank=True, choices=[('examination', 'Examination'), ('department', 'Department'), ('notice', 'Notics'), ('order', 'Order')], max_length=50, null=True),
        ),
    ]
