# Generated by Django 4.2.6 on 2024-07-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0010_alter_media_dept_alter_media_media_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.AlterField(
            model_name='media',
            name='media_category',
            field=models.CharField(blank=True, choices=[('Examination', 'Examination'), ('Eepartment', 'Department'), ('Notice', 'Notice'), ('Order', 'Order')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('AssistantProfessor', 'Assistant Professor'), ('associateProfessor', 'Associate Professor'), ('Professor', 'Professor'), ('GuestLecturer', 'Guest Lecturer'), ('Principal', 'Principal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trashmedia',
            name='media_category',
            field=models.CharField(blank=True, choices=[('Examination', 'Examination'), ('Department', 'Department'), ('Notice', 'Notics'), ('Order', 'Order')], max_length=50, null=True),
        ),
    ]
